name: Build and scan
on: [push]

jobs:
  build-scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build image
      run: docker build -t ${{ secrets.ECR_REPO }}:commit-${{ github.sha }} ./app

    - name: Trivy scan
      uses: aquasecurity/trivy-action@0.20.0
      with:
        image-ref: ${{ secrets.ECR_REPO }}:commit-${{ github.sha }}
        format: 'table'
        severity: 'HIGH,CRITICAL'
        exit-code: '1'

    - name: Push image on pass
      if: success()
      run: docker push ${{ secrets.ECR_REPO }}:commit-${{ github.sha }}